### ISSUE TITLE
[Refactoring] JSON

### ISSUE THREAD

**Issue by lorddaedra** [getlago/lago-python-client#73]
Motivation:

- Correct decomposition (we should not mix requests/responses and json encoding/decoding together)
- Reduce dependency on `requests` library (I think we on the road to use async `httpx` someday, async is good choice for I/O related tasks)
- Optimisations (today `orjson` looks like the best library for Python json processing)

Suggestions:

- [x] Create `services/json.py` module with functions (or classes with `__call__` method) responsible for json encoding/decoding, use them as wrapper around `orjson` library (we already ship it as dependency), this module should become the only module where we import `orjson` #74
- [x] Use these json services instead of `response.json()` or `import json ...` everywhere #76
- [x] Raise Lago Exception with 500 status code around `invalid json` or `empty data` case #79
